# -*- coding: utf-8 -*-
"""AI_Resume_Screening_System

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cqiLcfkSJELxUv4RMZT8NMMHzUJNAlxO
"""

#libraries
import fitz  # PyMuPDF
import faiss
import numpy as np
import pandas as pd
import streamlit as st
from google import genai
from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity
print("All libraries imported successfully!")

client = genai.Client(
    api_key=st.secrets["GEMINI_API_KEY"]
)
import streamlit as st
resume_file = st.file_uploader(
    "Upload Resume",
            type=["pdf"]
        )
        #extract text from resume
      

def extract_text_from_pdf(pdf_bytes):
    pdf = fitz.open(stream=pdf_bytes, filetype="pdf")

    text = ""

    for page in pdf:
        text += page.get_text()

    pdf.close()

    return text
st.write("Resume uploaded:", resume_file is not None)
resume_texts = {}
if resume_file is not None:
     resume_text = extract_text_from_pdf(resume_file.read())
     resume_texts[resume_file.name] = resume_text
    #display extracted text
for filename, text in resume_texts.items():
        print("=" * 80)
        print(f"Resume: {filename}")
        print("=" * 80)
        print(text[:2000])  # First 2000 characters
        print("\n")
"""Job Description Parser

    Instead of hardcoding the JD, we'll allow the recruiter to upload it."""
    #from google.colab import files

print("Upload the Job Description (TXT or PDF)")
jd_file = st.file_uploader(
        "Upload Job Description",
        type=["pdf"]
    )

    #extract jd text
jd_text = ""
if jd_file is not None:
        jd_text = extract_text_from_pdf(
            jd_file.read()
        )
print(jd_text[:3000])  # Print first 3000 characters
if st.button("Analyze Resume"):
    #run cleaning
    import re

    def clean_text(text):
        text = text.lower()
        text = re.sub(r"\n", " ", text)
        text = re.sub(r"\t", " ", text)
        text = re.sub(r"\s+", " ", text)
        text = re.sub(r"[^a-zA-Z0-9+#/. ]", "", text)
        return text.strip()

    clean_resume = {}

    for filename, text in resume_texts.items():
        clean_resume[filename] = clean_text(text)

    clean_jd = clean_text(jd_text)

    print(clean_jd[:1000])

    #Generate Embeddings
    #load model

    from sentence_transformers import SentenceTransformer

    # Load a lightweight embedding model
    model = SentenceTransformer("all-MiniLM-L6-v2")

    print("Model loaded successfully!")

    #generate embedding
    resume_embeddings = {}
    resume_names = []

    for filename, text in clean_resume.items():
        embedding = model.encode(text)
        resume_embeddings[filename] = embedding
        resume_names.append(filename)

    jd_embedding = model.encode(clean_jd)

    print("Embeddings generated successfully!")

    #run resume match code
    from sklearn.metrics.pairwise import cosine_similarity
    import pandas as pd

    results = []

    for filename, embedding in resume_embeddings.items():
        score = cosine_similarity(
            [jd_embedding],
            [embedding]
        )[0][0]

        results.append({
            "Resume": filename,
            "Match Score (%)": round(score * 100, 2)
        })

    print("Results =", results)

    df = pd.DataFrame(results)

    print("Columns =", df.columns.tolist())
    print(df)

    if df.empty:
        st.error("DataFrame is empty. No resume was processed.")
        st.stop()

    if "Match Score (%)" not in df.columns:
        st.error(f"Column not found. Available columns: {df.columns.tolist()}")
        st.stop()

    df = df.sort_values(by="Match Score (%)", ascending=False)
    df = df.sort_values(by="Match Score (%)", ascending=False)

    st.dataframe(df)


    


    response = client.models.generate_content(
        model="gemini-2.5-flash",
        contents="Say Hello"
    )

    print(response.text)

    #Extract Structured Information from the Job Description
    import json
    from google import genai
    resume_prompt = f"""
    Extract resume information...

    Resume:

    {resume_text}
    """

    response = client.models.generate_content(
        model="gemini-2.5-flash",
        contents=resume_prompt
    )
    st.write("Gemini Response:")
    st.code(response.text)
    resume_prompt = f"""
    You are an ATS Resume Parser.

    Extract the resume into JSON.

    Return ONLY valid JSON.

    Do NOT write explanations.

    Do NOT use markdown.

    Do NOT use ```json.

    Return ONLY this format:

    {{
        "candidate_name":"",
        "candidate_summary":"",
        "technical_skills":[],
        "soft_skills":[],
        "tools":[],
        "frameworks":[],
        "projects":[],
        "experience":"",
        "education":[]
    }}

    Resume:
    {resume_text}
    """

    response = client.models.generate_content(
        model="gemini-2.5-flash",
        contents=resume_prompt
    )

    resume_text_json = response.text.strip()
    resume_text_json = resume_text_json.replace("```json", "").replace("```", "").strip()

    resume_json = json.loads(resume_text_json)

    #st.subheader("Resume JSON")
    #st.json(resume_json)

    jd_prompt = f"""
    You are an ATS Job Description Parser.

    Extract the job description into JSON.

    Return ONLY valid JSON.

    Do NOT explain.

    Do NOT use markdown.

    Return ONLY:

    {{
        "job_title":"",
        "technical_skills":[],
        "frameworks":[],
        "cloud_platforms":[],
        "tools":[],
        "responsibilities":[]
    }}

    Job Description:

    {clean_jd}
    """
    response = client.models.generate_content(
        model="gemini-2.5-flash",
        contents=jd_prompt
    )

    jd_text_json = response.text.strip()
    jd_text_json = jd_text_json.replace("```json", "").replace("```", "").strip()

    jd_json = json.loads(jd_text_json)

    #st.subheader("JD JSON")
    #st.json(jd_json)

    #Analysis
    analysis_prompt = f"""
You are an ATS Hiring Assistant.

Compare the following Resume and Job Description.

Use the semantic match score exactly as provided.

Do NOT calculate a new score.

Return ONLY valid JSON.

Do NOT use markdown.

Do NOT explain anything.

Resume Match Score:
{df.iloc[0]["Match Score (%)"]:.2f}

Resume:
{resume_text}

Job Description:
{jd_text}

Return ONLY this JSON:

{{
  "candidate_summary": "",
  "match_score": "{df.iloc[0]['Match Score (%)']:.2f}",
  "matching_skills": [],
  "missing_skills": [],
  "strengths": [],
  "weaknesses": [],
  "experience_match": "",
  "education_match": "",
  "recommendation": "",
  "reason": "",
  "interview_questions": []
}}
"""
    response = client.models.generate_content(
    model="gemini-2.5-flash",
    contents=analysis_prompt,
    config={
        "response_mime_type": "application/json"
    }
)
    analysis = json.loads(response.text)
    st.subheader("👤 Candidate Summary")
    st.write(analysis["candidate_summary"])
    st.metric(
        "Resume Match Score",
        f"{analysis['match_score']} %"
    )

    import pandas as pd

    matching_df = pd.DataFrame({
        "Matched Skills": analysis["matching_skills"]
    })

    st.subheader("✅ Matching Skills")
    st.table(matching_df)
    missing_df = pd.DataFrame({
    "Missing Skills": analysis["missing_skills"]
    })

    st.subheader("❌ Missing Skills")
    st.table(missing_df)

    st.subheader("💪 Strengths")

    for s in analysis["strengths"]:
        st.success(s)
    
    st.subheader("⚠ Weaknesses")
    for w in analysis["weaknesses"]:
        st.warning(w)
    col1, col2 = st.columns(2)

    with col1:
        st.subheader("📌 Experience")
        st.info(analysis["experience_match"])

    with col2:
        st.subheader("🎓 Education")
        st.info(analysis["education_match"])
    
    st.subheader("⭐ Recommendation")

    st.success(analysis["recommendation"])

    st.write(analysis["reason"])
    st.subheader("❓ Interview Questions")

    for i, q in enumerate(analysis["interview_questions"], start=1):
        st.write(f"**{i}.** {q}")